name: Choco Build and Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Value from the version field in pom.xml. i.e 4.26.0"
        type: string
        required: true
      dry_run: 
        description: 'Flag to indicate if the workflow is triggered to create a dry-run release'
        required: true
        type: boolean
        default: false
  workflow_call:
    inputs:
      version:
        description: "Value from the version field in pom.xml. i.e 4.26.0"
        type: string
        required: true
      dry_run: 
        description: 'Flag to indicate if the workflow is triggered to create a dry-run release'
        required: true
        type: boolean
        default: false

jobs:
  build_and_deploy:
    runs-on: windows-latest
    env:
      LIQUIBASE_VERSION: ${{ inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: liquibase/liquibase-chocolatey

      - name: Set up Java 17 (Temurin)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
    
      - name: Verify Java version
        run: java -version

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install Ant
        run: choco install ant

      - name: Build nupkg Chocolatey package
        run: ant make-nuspec

      - name: Choco pack
        run: |
          choco pack

      - name: Install Temurin 17
        run: choco install temurin17

      - name: Choco install
        run: |
          choco install liquibase --version="${{ inputs.version }}" --source="." --debug --verbose
          liquibase --version

      - name: Choco push
        if: ${{ inputs.dry_run == false }}
        run: |
          choco push liquibase.${{ inputs.version }}.nupkg --source "'https://push.chocolatey.org/'" --key "${{secrets.CHOCO_APIKEY}}" --debug --verbose
